name: Bug report
description: Report a problem with lazylinear
title: "bug: "
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: lazylinear version
      description: Output of `linear --version`
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      description: Output of `python --version`
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
