#!/usr/bin/env python3
"""Generate command reference documentation from linear --help output.

Usage:
    python scripts/generate_docs.py > docs/commands.md
"""

from __future__ import annotations

import os
import subprocess
import sys

COMMANDS = [
    ([], "linear"),
    (["viewer"], "viewer"),
    (["teams"], "teams"),
    (["states"], "states"),
    (["issues"], "issues"),
    (["read"], "read"),
    (["create"], "create"),
    (["move"], "move"),
    (["comment"], "comment"),
    (["comments"], "comments"),
    (["query"], "query"),
]


def get_help(args: list[str]) -> str:
    cmd = [sys.executable, "-m", "lazylinear"] + args + ["--help"]
    env = {**os.environ, "COLUMNS": "100"}
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=10, check=False, env=env)
    return result.stdout or result.stderr


def main() -> None:
    print("# Command Reference")
    print()
    print("> Auto-generated from `linear --help`. Do not edit manually.")
    print()

    for args, _name in COMMANDS:
        help_text = get_help(args)
        if not help_text.strip():
            continue
        level = "##" if not args else "###"
        command = "linear" + (" " + " ".join(args) if args else "")
        print(f"{level} `{command}`")
        print()
        print("```")
        print(help_text.rstrip())
        print("```")
        print()

    print("---")
    print()
    print("*Generated by `scripts/generate_docs.py`*")


if __name__ == "__main__":
    main()
